language: ruby
jobs:
  include:
  - name: DPL Lambda NodeJS 18 deploy
    os: linux
    language: ruby
    rvm: 3.3
    deploy:
      provider: lambda
      function_name: "lambda-test"
      region: "us-east-1"
      role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
      runtime: "nodejs18.x"
      handler_name: "handler"
      on:
        branch: dpl-test
      edge:
        branch: tbt_4_am